### ISSUE TITLE
打卡系统更换

### ISSUE THREAD

**Issue by HardLeft1004** [windiboy/BUAAAutoUpdate#2]
首先先感谢下您提供的脚本，之前一直在用，想问下现在换打卡系统了，之后还会更新相应脚本么？

**Comment by windiboy** [comment]
会的，我这周末更新一下，感谢支持😃



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Zhaowei-Yu <notifications@github.com&gt;
发送时间: 2021年3月3日 17:21
收件人: windiboy/BUAAAutoUpdate <BUAAAutoUpdate@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[windiboy/BUAAAutoUpdate] 打卡系统更换 (#2)





 
首先先感谢下您提供的脚本，之前一直在用，想问下现在换打卡系统了，之后还会更新相应脚本么？
