### ISSUE TITLE
在自己的仓库配置workflow时出错，望解答（提前感谢！）

### ISSUE THREAD

**Issue by arounderor** [windiboy/BUAAAutoUpdate#7]
![image](https://user-images.githubusercontent.com/78290676/131308363-c399efb8-f0cb-46a1-8b04-50b914adf323.png)
手动运行auto_check时显示找不到 FORM_DATA，其他几个环境变量都没问题
在源文件中将os.environ["FORM_DATA"]以字符串形式输入能正常运行。

**Comment by arounderor** [comment]
在 settings environment 里配置好 secrets, yaml文件对应部分没有修改😰

**Comment by ywz978020607** [comment]
这个是字典格式，怎么放进secret呀，用github-action一直有格式问题

**Comment by windiboy** [comment]
信件已收到。
